language: c

matrix:
  include:
    - os: linux
      arch: amd64
      dist: focal
      compiler: gcc
    - os: linux
      arch: amd64
      dist: focal
      compiler: clang
    - os: linux
      arch: arm64
      dist: focal
      compiler: gcc
    - os: linux
      arch: amd64
      dist: bionic
      compiler: gcc
    - os: linux
      arch: amd64
      dist: xenial
      compiler: gcc
    - os: linux
      arch: amd64
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang
    - os: windows
      script:
        - mkdir -p build
        - cd build
        - cmake .. 
        - nmake

script:
  - mkdir -p build
  - cd build
  - cmake .. 
  - make

sudo: false

notifications:
  email: false
