language: c

matrix:
  include:
    - os: linux
      arch: amd64
      dist: focal
      env:
        - MAKE="make"
    - os: linux
      arch: amd64
      dist: focal
      env:
        - MAKE="make"
    - os: linux
      arch: arm64
      dist: focal
      env:
        - MAKE="make"
    - os: linux
      arch: amd64
      dist: bionic
      env:
        - MAKE="make"
    - os: linux
      arch: amd64
      dist: xenial
      env:
        - MAKE="make"
    - os: linux
      arch: amd64
      dist: trusty
      env:
        - MAKE="make"
    - os: osx
      env:
        - MAKE="make"
    - os: windows
      env:
        - MAKE="nmake"

os:
  - linux
  - osx
  - windows

compiler:
  - clang
  - gcc

script:
  - mkdir -p build
  - cd build
  - cmake .. 
  - ${MAKE}

sudo: false

notifications:
  email: false
